name: mathstudio2
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  uuid: ^3.0.7

  english_words: ^4.0.0
  provider: ^6.1.2
  js: ^0.7.1
  material: ^1.0.0+2
  flutter_math_fork: ^0.7.3
  flutter_markdown: ^0.7.6
  url_launcher: ^6.3.1
  markdown: ^7.3.0
  google_fonts: ^6.2.1
  highlight: ^0.7.0
  math_expressions: ^2.6.0
  fl_chart: ^0.70.2
  expressions: ^0.2.5+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true